<a href="https://colab.research.google.com/github/Trading-com-Dados/desenvolvimento_interno/blob/main/20220413_Backtesting_a_mao_monitoria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# **BACKTESTING  "*à mão*": o céu é o limite!** 
---
#### *Disclaimer:*
#### Este código foi elaborado para fins exclusivamente educacionais. O conteúdo aqui apresentado visa fornecer informações complementares para auxiliar o investidor na tomada de suas próprias decisões de investimento. Reforçando, nenhum tópico aqui abordado constitui qualquer tipo de indicação/oferta/solicitação de compra/venda de qualquer produto.
---

<img src="https://tradingcomdados.com/images/logotipo/logotipo-trading-com-dados.svg" width="300">

# **1. Bibliotecas utilizadas**

In [6]:
!pip install yfinance
!pip install python-binance
!pip install ta

Requirement already satisfied: yfinance in /usr/local/lib/python3.7/dist-packages (0.1.70)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.8.0)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.5)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.27.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Collecting python-binance
  Downloading python_binance-1.0.16-py2.py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 2.4 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from python-binance) (2.27.1)
Collecting aiohttp
  Downloading aiohttp-3.8.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 10.9 MB/s
Collecting ujson
  Downloading ujson-5.2.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (45 kB)
     |████████████████████████████████| 45 kB 2.9 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from python-binance) (1.15.0)
Collecting websockets
  Downloading websockets-10.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (111 kB)
     |████████████████████████████████| 111 kB 52.5 MB/s
Collecting dateparser
  Downloading dateparser-1.1.1-py2.py3-none-any.whl (288 kB)
     |████████████████████████████████| 288 kB 56.3 MB/s
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->python-binance) (2.0.12)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271 kB)
     |████████████████████████████████| 271 kB 56.0 MB/s
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (94 kB)
     |████████████████████████████████| 94 kB 3.6 MB/s
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
     |████████████████████████████████| 144 kB 62.1 MB/s
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from aiohttp->python-binance) (4.1.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->python-binance) (21.4.0)
Collecting asynctest==0.13.0
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp->python-binance) (2.10)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (2018.9)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (2.8.2)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (1.5.1)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27,<2022.3.15 in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (2019.12.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->python-binance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->python-binance) (2021.10.8)
Installing collected packages: multidict, frozenlist, yarl, asynctest, async-timeout, aiosignal, websockets, ujson, dateparser, aiohttp, python-binance
Successfully installed aiohttp-3.8.1 aiosignal-1.2.0 async-timeout-4.0.2 asynctest-0.13.0 dateparser-1.1.1 frozenlist-1.3.0 multidict-6.0.2 python-binance-1.0.16 ujson-5.2.0 websockets-10.2 yarl-1.7.2
Requirement already satisfied: ta in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from ta) (1.21.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from ta) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->ta) (1.15.0)

In [70]:
import numpy as np
import pandas as pd
from datetime import datetime
import pytz

import yfinance as yf
from binance.client import Client
import ta

import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

# **2. Definir o setup e baixar os dados**

## 2.1. Definir sinais de Entrada

---
**OBS.: Durante a aula do dia 13/04/22 acabei me confundindo e misturando os dois setups abaixo**

---

**Preço de fechamento de reversão**

Sinal de Entrada:<p>
1) Quando a mínima do candle atual for menor do que a mínima dos dois últimos candles prévios e; <p>
2) o fechamento do candle atual for maior do que o fechamento do candle anterior.

**123 de compra simples**

Sinal de Entrada:<p>
1) Um candle que tenha a mínima menor que a mínima do candle anterior e; <p>
2) Vamos comprar na superação da máxima desse candle formando os três candles e, <p>
3) Isso em cima da MM9 ascendente.

---
**Mas vamos aproveitar e colocar os dois em prática para comparar os resultados**

---

## 2.2. Baixar os dados (yfinance ou binance)

In [35]:
# Os conjuntos de dados das bibliotecas são padronizados em UTC (horário padrão global =  Brasília - 3h)

hora_agora_BR = datetime.now(pytz.timezone("America/Sao_Paulo"))
hora_agora_BR

datetime.datetime(2022, 4, 13, 22, 51, 25, 989934, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>)

In [37]:
# Acho que Bitcoin pelo Yahoo Finance só em dolar mesmo
# Dependendo do horário em que o código for rodado, os candles já corresponderão ao dia de amanhã

cotacoes_BTC_yf = yf.download("BTC-USD", start = '2018-04-01', interval = "1D")
cotacoes_BTC_yf

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-04-01,7003.060059,7060.950195,6526.870117,6844.229980,6844.229980,4532100096
2018-04-02,6844.859863,7135.470215,6816.580078,7083.799805,7083.799805,4333440000
2018-04-03,7102.259766,7530.939941,7072.490234,7456.109863,7456.109863,5499700224
2018-04-04,7456.410156,7469.879883,6803.879883,6853.839844,6853.839844,4936000000
2018-04-05,6848.649902,6933.819824,6644.799805,6811.470215,6811.470215,5639320064
...,...,...,...,...,...,...
2022-04-09,42282.078125,42786.816406,42183.253906,42782.136719,42782.136719,16050772496
2022-04-10,42781.089844,43376.378906,42021.207031,42207.671875,42207.671875,17654475582
2022-04-11,42201.039062,42424.589844,39373.058594,39521.902344,39521.902344,33949912166
2022-04-12,39533.714844,40617.585938,39388.328125,40127.183594,40127.183594,30991500854
2022-04-14,41099.535156,41353.925781,41099.535156,41336.894531,41336.894531,27713646592

In [38]:
# Utilizando a python-binance (possui BTC em BRL)
# Um pouco mais complexo o início para produzir o dataframe final

api_secret = 'nao_necessario_para_cotacoes'
api_key = 'apenas_para_trading_real'

In [39]:
end_str = datetime.now(pytz.timezone("UTC")).strftime("%Y-%m-%d")
end_str

'2022-04-14'

In [47]:
client = Client()
cotacoes_BTC_BRL = client.get_historical_klines(symbol='BTCBRL', start_str = '2018-04-01', end_str = end_str, interval=Client.KLINE_INTERVAL_1DAY)
cotacoes_BTC_BRL[0:2]

[[1602547200000,
  '63606.00000000',
  '64059.00000000',
  '46208.00000000',
  '63921.00000000',
  '2.87607300',
  1602633599999,
  '181785.88362100',
  370,
  '2.32937400',
  '147274.38088300',
  '0'],
 [1602633600000,
  '63920.00000000',
  '64314.00000000',
  '62677.00000000',
  '64068.00000000',
  '7.02546000',
  1602719999999,
  '447815.98757600',
  519,
  '4.47722500',
  '285514.69429100',
  '0']]

In [41]:
BTC_BRL_df = pd.DataFrame(cotacoes_BTC_BRL)
BTC_BRL_df

,0,1,2,3,4,5,6,7,8,9,10,11
0,1602547200000,63606.00000000,64059.00000000,46208.00000000,63921.00000000,2.87607300,1602633599999,181785.88362100,370,2.32937400,147274.38088300,0
1,1602633600000,63920.00000000,64314.00000000,62677.00000000,64068.00000000,7.02546000,1602719999999,447815.98757600,519,4.47722500,285514.69429100,0
2,1602720000000,64068.00000000,65764.00000000,63505.00000000,65314.00000000,10.53093500,1602806399999,682399.26519400,498,9.31532100,603488.37039800,0
3,1602806400000,65334.00000000,65560.00000000,63650.00000000,64750.00000000,9.18102600,1602892799999,593389.07995100,447,5.74067700,371335.12349600,0
4,1602892800000,64600.00000000,65025.00000000,64418.00000000,64665.00000000,1.89171500,1602979199999,122331.44754300,101,1.06647100,69085.62068600,0
...,...,...,...,...,...,...,...,...,...,...,...,...
544,1649548800000,202979.00000000,205920.00000000,198599.00000000,200204.00000000,166.81185000,1649635199999,33818456.85436000,12798,75.56504000,15330424.59228000,0
545,1649635200000,200065.00000000,201081.00000000,185915.00000000,187418.00000000,498.96877000,1649721599999,96521904.97028000,34941,219.18860000,42424712.97338000,0
546,1649721600000,187441.00000000,192407.00000000,185156.00000000,188910.00000000,470.54003000,1649807999999,88745371.73495000,26302,229.59564000,43320981.79753000,0
547,1649808000000,189000.00000000,195770.00000000,186200.00000000,194543.00000000,384.42073000,1649894399999,73537558.90339000,19572,189.66631000,36329424.24103000,0
548,1649894400000,194565.00000000,195581.00000000,194075.00000000,195581.00000000,18.76629000,1649980799999,3655881.26831000,1305,10.69120000,2083126.53319000,0

Lista das colunas obtidas (Open time, Open, High, Low, Close, Volume, Close time, Quote asset volume, Number of trades, Taker buy base asset volume, Taker buy quote asset volume, Ignore)

In [42]:
list(enumerate(['Open time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close time', 'Quote asset volume', 'Number of trades', 'Taker buy base asset volume', 'Taker buy quote asset volume', 'Ignore']))

[(0, 'Open time'),
 (1, 'Open'),
 (2, 'High'),
 (3, 'Low'),
 (4, 'Close'),
 (5, 'Volume'),
 (6, 'Close time'),
 (7, 'Quote asset volume'),
 (8, 'Number of trades'),
 (9, 'Taker buy base asset volume'),
 (10, 'Taker buy quote asset volume'),
 (11, 'Ignore')]

In [43]:
BTC_BRL_df.rename(columns={0:'Date',1:'Open',2:'High',3:'Low',4:'Close',5:'Volume'},inplace=True)
BTC_BRL_df.set_index('Date', inplace=True)
BTC_BRL_df

,Open,High,Low,Close,Volume,6,7,8,9,10,11
Date,,,,,,,,,,,
1602547200000,63606.00000000,64059.00000000,46208.00000000,63921.00000000,2.87607300,1602633599999,181785.88362100,370,2.32937400,147274.38088300,0
1602633600000,63920.00000000,64314.00000000,62677.00000000,64068.00000000,7.02546000,1602719999999,447815.98757600,519,4.47722500,285514.69429100,0
1602720000000,64068.00000000,65764.00000000,63505.00000000,65314.00000000,10.53093500,1602806399999,682399.26519400,498,9.31532100,603488.37039800,0
1602806400000,65334.00000000,65560.00000000,63650.00000000,64750.00000000,9.18102600,1602892799999,593389.07995100,447,5.74067700,371335.12349600,0
1602892800000,64600.00000000,65025.00000000,64418.00000000,64665.00000000,1.89171500,1602979199999,122331.44754300,101,1.06647100,69085.62068600,0
...,...,...,...,...,...,...,...,...,...,...,...
1649548800000,202979.00000000,205920.00000000,198599.00000000,200204.00000000,166.81185000,1649635199999,33818456.85436000,12798,75.56504000,15330424.59228000,0
1649635200000,200065.00000000,201081.00000000,185915.00000000,187418.00000000,498.96877000,1649721599999,96521904.97028000,34941,219.18860000,42424712.97338000,0
1649721600000,187441.00000000,192407.00000000,185156.00000000,188910.00000000,470.54003000,1649807999999,88745371.73495000,26302,229.59564000,43320981.79753000,0
1649808000000,189000.00000000,195770.00000000,186200.00000000,194543.00000000,384.42073000,1649894399999,73537558.90339000,19572,189.66631000,36329424.24103000,0
1649894400000,194565.00000000,195581.00000000,194075.00000000,195581.00000000,18.76629000,1649980799999,3655881.26831000,1305,10.69120000,2083126.53319000,0

In [44]:
BTC_BRL_df.index = pd.to_datetime(BTC_BRL_df.index,unit='ms')
BTC_BRL_df = BTC_BRL_df.drop(BTC_BRL_df.columns[5:],axis=1)
BTC_BRL_df

,Open,High,Low,Close,Volume
Date,,,,,
2020-10-13,63606.00000000,64059.00000000,46208.00000000,63921.00000000,2.87607300
2020-10-14,63920.00000000,64314.00000000,62677.00000000,64068.00000000,7.02546000
2020-10-15,64068.00000000,65764.00000000,63505.00000000,65314.00000000,10.53093500
2020-10-16,65334.00000000,65560.00000000,63650.00000000,64750.00000000,9.18102600
2020-10-17,64600.00000000,65025.00000000,64418.00000000,64665.00000000,1.89171500
...,...,...,...,...,...
2022-04-10,202979.00000000,205920.00000000,198599.00000000,200204.00000000,166.81185000
2022-04-11,200065.00000000,201081.00000000,185915.00000000,187418.00000000,498.96877000
2022-04-12,187441.00000000,192407.00000000,185156.00000000,188910.00000000,470.54003000
2022-04-13,189000.00000000,195770.00000000,186200.00000000,194543.00000000,384.42073000
2022-04-14,194565.00000000,195581.00000000,194075.00000000,195581.00000000,18.76629000

In [71]:
BTC_BRL_df['Open'] = pd.to_numeric(BTC_BRL_df['Open'])
BTC_BRL_df['High'] = pd.to_numeric(BTC_BRL_df['High'])
BTC_BRL_df['Low'] = pd.to_numeric(BTC_BRL_df['Low'])
BTC_BRL_df['Close'] = pd.to_numeric(BTC_BRL_df['Close'])
BTC_BRL_df['Volume'] = pd.to_numeric(BTC_BRL_df['Volume'])
BTC_BRL_df

                Open      High       Low     Close      Volume
Date
2020-10-13   63606.0   64059.0   46208.0   63921.0    2.876073
2020-10-14   63920.0   64314.0   62677.0   64068.0    7.025460
2020-10-15   64068.0   65764.0   63505.0   65314.0   10.530935
2020-10-16   65334.0   65560.0   63650.0   64750.0    9.181026
2020-10-17   64600.0   65025.0   64418.0   64665.0    1.891715
...              ...       ...       ...       ...         ...
2022-04-10  202979.0  205920.0  198599.0  200204.0  166.811850
2022-04-11  200065.0  201081.0  185915.0  187418.0  498.968770
2022-04-12  187441.0  192407.0  185156.0  188910.0  470.540030
2022-04-13  189000.0  195770.0  186200.0  194543.0  384.420730
2022-04-14  194565.0  195581.0  194075.0  195581.0   18.766290

[549 rows x 5 columns]

---
**PAUSA (INICIO): Duvida durante plantão: Teste volume ao longo do dia das criptos**

---

In [72]:
client = Client()
btc_df = client.get_historical_klines(symbol='BTCBRL', start_str = '2022-03-01', end_str = end_str, interval=Client.KLINE_INTERVAL_30MINUTE)

btc_df = pd.DataFrame(btc_df)
btc_df.rename(columns={0:'Open time',1:'open',2:'high',3:'low',4:'close',5:'volume',6:'Close time'},inplace=True)
#btc_df.set_index('date', inplace=True)
btc_df['Open time'] = pd.to_datetime(btc_df['Open time'],unit='ms')
btc_df['Close time'] = pd.to_datetime(btc_df['Close time'],unit='ms')
btc_df = btc_df.drop(btc_df.columns[7:],axis=1)
btc_df['open'] = pd.to_numeric(btc_df['open'])
btc_df['high'] = pd.to_numeric(btc_df['high'])
btc_df['low'] = pd.to_numeric(btc_df['low'])
btc_df['close'] = pd.to_numeric(btc_df['close'])
btc_df['volume'] = pd.to_numeric(btc_df['volume'])
btc_df

,Open time,open,high,low,close,volume,Close time
0,2022-03-01 00:00:00,222697.0,224857.0,222652.0,223617.0,8.01033,2022-03-01 00:29:59.999
1,2022-03-01 00:30:00,223567.0,225343.0,223365.0,224649.0,11.92042,2022-03-01 00:59:59.999
2,2022-03-01 01:00:00,224615.0,224825.0,222637.0,222843.0,6.36851,2022-03-01 01:29:59.999
3,2022-03-01 01:30:00,222907.0,223686.0,222692.0,222770.0,8.26647,2022-03-01 01:59:59.999
4,2022-03-01 02:00:00,222775.0,222998.0,221368.0,221703.0,7.73150,2022-03-01 02:29:59.999
...,...,...,...,...,...,...,...
2108,2022-04-13 22:00:00,194917.0,195330.0,194648.0,195089.0,3.28894,2022-04-13 22:29:59.999
2109,2022-04-13 22:30:00,195225.0,195577.0,194650.0,194959.0,3.71596,2022-04-13 22:59:59.999
2110,2022-04-13 23:00:00,195031.0,195180.0,194050.0,194446.0,6.09422,2022-04-13 23:29:59.999
2111,2022-04-13 23:30:00,194416.0,194761.0,194200.0,194543.0,2.37627,2022-04-13 23:59:59.999
2112,2022-04-14 00:00:00,194565.0,194755.0,194075.0,194700.0,4.70843,2022-04-14 00:29:59.999

In [73]:
btc_df['Hora'] = pd.to_datetime(btc_df['Close time']).dt.strftime('%H')
btc_df['Dia_mes'] = pd.to_datetime(btc_df['Close time']).dt.strftime('%m-%d')
btc_df

,Open time,open,high,low,close,volume,Close time,Hora,Dia_mes
0,2022-03-01 00:00:00,222697.0,224857.0,222652.0,223617.0,8.01033,2022-03-01 00:29:59.999,00,03-01
1,2022-03-01 00:30:00,223567.0,225343.0,223365.0,224649.0,11.92042,2022-03-01 00:59:59.999,00,03-01
2,2022-03-01 01:00:00,224615.0,224825.0,222637.0,222843.0,6.36851,2022-03-01 01:29:59.999,01,03-01
3,2022-03-01 01:30:00,222907.0,223686.0,222692.0,222770.0,8.26647,2022-03-01 01:59:59.999,01,03-01
4,2022-03-01 02:00:00,222775.0,222998.0,221368.0,221703.0,7.73150,2022-03-01 02:29:59.999,02,03-01
...,...,...,...,...,...,...,...,...,...
2108,2022-04-13 22:00:00,194917.0,195330.0,194648.0,195089.0,3.28894,2022-04-13 22:29:59.999,22,04-13
2109,2022-04-13 22:30:00,195225.0,195577.0,194650.0,194959.0,3.71596,2022-04-13 22:59:59.999,22,04-13
2110,2022-04-13 23:00:00,195031.0,195180.0,194050.0,194446.0,6.09422,2022-04-13 23:29:59.999,23,04-13
2111,2022-04-13 23:30:00,194416.0,194761.0,194200.0,194543.0,2.37627,2022-04-13 23:59:59.999,23,04-13
2112,2022-04-14 00:00:00,194565.0,194755.0,194075.0,194700.0,4.70843,2022-04-14 00:29:59.999,00,04-14

In [74]:
volume_horas_bitcoin = btc_df.pivot_table(values='volume',index='Hora',columns=[],aggfunc=np.sum)
volume_horas_bitcoin

          volume
Hora
00     652.80632
01     671.48896
02     568.06708
03     449.87732
04     431.68127
05     298.08396
06     253.88052
07     261.85531
08     313.85691
09     423.77767
10     444.26163
11     624.05214
12    1101.28198
13    1196.90684
14    1172.80161
15    1160.45585
16    1061.40826
17     934.40470
18    1013.94013
19     966.95449
20     935.41425
21     546.18250
22     593.99289
23     568.69115

In [80]:
fig = px.histogram(volume_horas_bitcoin, x=volume_horas_bitcoin.index,y='volume')
fig.update_layout(xaxis_rangeslider_visible=False, title_text='Volume ao longo das horas (lembrando que está em UTC)',width=800 ,height=800)
fig.show()

---
**PAUSA (FIM): Duvida durante plantão: Teste volume ao longo do dia das criptos**

---

# **3. Backtesting Setup Preço de fechamento de reversão (PFR)**

* Bitcoin BRL<p>
* Timeframe diário
* Entre 2018 e o dia de hoje (ver o dia)

In [106]:
BTC_BRL_df

                Open      High       Low     Close      Volume
Date
2020-10-13   63606.0   64059.0   46208.0   63921.0    2.876073
2020-10-14   63920.0   64314.0   62677.0   64068.0    7.025460
2020-10-15   64068.0   65764.0   63505.0   65314.0   10.530935
2020-10-16   65334.0   65560.0   63650.0   64750.0    9.181026
2020-10-17   64600.0   65025.0   64418.0   64665.0    1.891715
...              ...       ...       ...       ...         ...
2022-04-10  202979.0  205920.0  198599.0  200204.0  166.811850
2022-04-11  200065.0  201081.0  185915.0  187418.0  498.968770
2022-04-12  187441.0  192407.0  185156.0  188910.0  470.540030
2022-04-13  189000.0  195770.0  186200.0  194543.0  384.420730
2022-04-14  194565.0  195581.0  194075.0  195581.0   18.766290

[549 rows x 5 columns]

**Preço de fechamento de reversão**

Sinal de Entrada:<p>
1) Quando a mínima do candle atual for menor do que a mínima dos dois últimos candles prévios e; <p>
2) O fechamento do candle atual for maior do que o fechamento do candle anterior.

**Regra 1:** Low2 < (Low1 e Low0)

**Regra 2:** Close2 > Close1

## **3.1. Sinais de entrada COMPRA e ordem Buy Limit**

**Regra 1:** Low2 < (Low1 e Low0)

In [85]:
# closed = 'left' exclui o próprio valor

min_2cd_ant = BTC_BRL_df['Low'].rolling(window=2,closed='left').min()
min_2cd_ant

Date
2020-10-13         NaN
2020-10-14         NaN
2020-10-15     46208.0
2020-10-16     62677.0
2020-10-17     63505.0
                ...
2022-04-10    199846.0
2022-04-11    198599.0
2022-04-12    185915.0
2022-04-13    185156.0
2022-04-14    185156.0
Name: Low, Length: 549, dtype: float64

---
**PAUSA (INICIO): Para entender melhor o parâmetro 'closed' de rolling**

---

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html

In [100]:
df_teste = pd.DataFrame({'A':list(range(0,5))})
df_teste

   A
0  0
1  1
2  2
3  3
4  4

In [101]:
# Left "exclui o valor dela mesma"
df_teste['min_left'] = df_teste['A'].rolling(window=1,closed='left').min()
df_teste['max_left'] = df_teste['A'].rolling(window=1,closed='left').max()
df_teste

   A  min_left  max_left
0  0       NaN       NaN
1  1       0.0       0.0
2  2       1.0       1.0
3  3       2.0       2.0
4  4       3.0       3.0

In [102]:
# Left "exclui o valor dela mesma"
df_teste['min_left'] = df_teste['A'].rolling(window=2,closed='left').min()
df_teste['max_left'] = df_teste['A'].rolling(window=2,closed='left').max()
df_teste

   A  min_left  max_left
0  0       NaN       NaN
1  1       NaN       NaN
2  2       0.0       1.0
3  3       1.0       2.0
4  4       2.0       3.0

In [103]:
# Right inclui o valor dela mesma mas exclui o que seria o primeiro

df_teste['min_left'] = df_teste['A'].rolling(window=1,closed='right').min()
df_teste['max_left'] = df_teste['A'].rolling(window=1,closed='right').max()
df_teste

   A  min_left  max_left
0  0       0.0       0.0
1  1       1.0       1.0
2  2       2.0       2.0
3  3       3.0       3.0
4  4       4.0       4.0

In [104]:
# Right inclui o valor dela mesma mas exclui o que seria o primeiro

df_teste['min_left'] = df_teste['A'].rolling(window=2,closed='right').min()
df_teste['max_left'] = df_teste['A'].rolling(window=2,closed='right').max()
df_teste

   A  min_left  max_left
0  0       NaN       NaN
1  1       0.0       1.0
2  2       1.0       2.0
3  3       2.0       3.0
4  4       3.0       4.0

---
**PAUSA (FIM): Para entender melhor o parâmetro 'closed' de rolling**

---

In [141]:
## Várias formas de analisar as mínimas dos últimos dois candles (sem considerar o próprio candle)

min_2cd_ant = BTC_BRL_df['Low'].rolling(window=2,closed='left').min()
BTC_BRL_df['min_2cd_ant'] = min_2cd_ant
BTC_BRL_df.head()

,Open,High,Low,Close,Volume,min_2cd_ant,min_2cd_ant_shift,min_2cd_ant_iloc,Equal_1_2
Date,,,,,,,,,
2020-10-13,63606.0,64059.0,46208.0,63921.0,2.876073,NaN,NaN,NA,False
2020-10-14,63920.0,64314.0,62677.0,64068.0,7.025460,NaN,NaN,NA,False
2020-10-15,64068.0,65764.0,63505.0,65314.0,10.530935,46208.0,46208.0,46208.0,True
2020-10-16,65334.0,65560.0,63650.0,64750.0,9.181026,62677.0,62677.0,62677.0,True
2020-10-17,64600.0,65025.0,64418.0,64665.0,1.891715,63505.0,63505.0,63505.0,True

In [164]:
BTC_BRL_df['Low'].shift(2)[2]

46208.0

In [173]:
## Mínima dos últimos 2 candles (outra forma)

list_min_2cd_ant_shift = ["NA"]

for i in range(0,len(BTC_BRL_df)-1):
  min_2cd_ant_shift = min( BTC_BRL_df['Low'].shift(1)[i], BTC_BRL_df['Low'].shift(2)[i])
  list_min_2cd_ant_shift.append(min_2cd_ant_shift)

In [174]:
len(list_min_2cd_ant_shift)

549

In [175]:
## Mínima dos últimos 2 candles (mais uma alternativa usando o iloc)

lista_min_2cd_ant_iloc = ["NA","NA"]

for i in range(0,len(BTC_BRL_df)-2):
  min_2cd_ant_iloc = min( BTC_BRL_df['Low'].iloc[i-len(BTC_BRL_df)], BTC_BRL_df['Low'].iloc[i-len(BTC_BRL_df)+1] )
  lista_min_2cd_ant_iloc.append(min_2cd_ant_iloc)

In [176]:
lista_min_2cd_ant_iloc[0:10]

['NA',
 'NA',
 46208.0,
 62677.0,
 63505.0,
 63650.0,
 64418.0,
 64867.0,
 65112.0,
 66398.0]

In [177]:
print(len(BTC_BRL_df))
print(len(lista_min_2cd_ant_iloc))

549
549

In [178]:
BTC_BRL_df['min_2cd_ant_iloc'] = lista_min_2cd_ant_iloc
BTC_BRL_df

,Open,High,Low,Close,Volume,min_2cd_ant,min_2cd_ant_shift,min_2cd_ant_iloc,Equal_1_2,Equal_1_3,Equal_2_3
Date,,,,,,,,,,,
2020-10-13,63606.0,64059.0,46208.0,63921.0,2.876073,NaN,NaN,NA,False,False,False
2020-10-14,63920.0,64314.0,62677.0,64068.0,7.025460,NaN,NaN,NA,False,False,False
2020-10-15,64068.0,65764.0,63505.0,65314.0,10.530935,46208.0,46208.0,46208.0,True,True,True
2020-10-16,65334.0,65560.0,63650.0,64750.0,9.181026,62677.0,62677.0,62677.0,True,True,True
2020-10-17,64600.0,65025.0,64418.0,64665.0,1.891715,63505.0,63505.0,63505.0,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
2022-04-10,202979.0,205920.0,198599.0,200204.0,166.811850,199846.0,199846.0,199846.0,True,True,True
2022-04-11,200065.0,201081.0,185915.0,187418.0,498.968770,198599.0,199860.0,198599.0,False,True,False
2022-04-12,187441.0,192407.0,185156.0,188910.0,470.540030,185915.0,198599.0,185915.0,False,True,False
2022-04-13,189000.0,195770.0,186200.0,194543.0,384.420730,185156.0,185915.0,185156.0,False,True,False
2022-04-14,194565.0,195581.0,194075.0,195581.0,18.766290,185156.0,185156.0,185156.0,True,True,True

In [179]:
# Checar se todas as três colunas são idênticas

BTC_BRL_df['min_2cd_ant_shift'].equals(BTC_BRL_df['min_2cd_ant_iloc'])

#BTC_BRL_df['min_2cd_ant'] == BTC_BRL_df['min_2cd_ant_shift'] == BTC_BRL_df['min_2cd_ant_iloc']

False

In [180]:
BTC_BRL_df["Equal_1_2"] = BTC_BRL_df['min_2cd_ant'] == BTC_BRL_df['min_2cd_ant_shift']
BTC_BRL_df["Equal_1_3"] = BTC_BRL_df['min_2cd_ant'] == BTC_BRL_df['min_2cd_ant_iloc']
BTC_BRL_df["Equal_2_3"] = BTC_BRL_df['min_2cd_ant_shift'] == BTC_BRL_df['min_2cd_ant_iloc']
BTC_BRL_df

,Open,High,Low,Close,Volume,min_2cd_ant,min_2cd_ant_shift,min_2cd_ant_iloc,Equal_1_2,Equal_1_3,Equal_2_3
Date,,,,,,,,,,,
2020-10-13,63606.0,64059.0,46208.0,63921.0,2.876073,NaN,NaN,NA,False,False,False
2020-10-14,63920.0,64314.0,62677.0,64068.0,7.025460,NaN,NaN,NA,False,False,False
2020-10-15,64068.0,65764.0,63505.0,65314.0,10.530935,46208.0,46208.0,46208.0,True,True,True
2020-10-16,65334.0,65560.0,63650.0,64750.0,9.181026,62677.0,62677.0,62677.0,True,True,True
2020-10-17,64600.0,65025.0,64418.0,64665.0,1.891715,63505.0,63505.0,63505.0,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
2022-04-10,202979.0,205920.0,198599.0,200204.0,166.811850,199846.0,199846.0,199846.0,True,True,True
2022-04-11,200065.0,201081.0,185915.0,187418.0,498.968770,198599.0,199860.0,198599.0,False,True,False
2022-04-12,187441.0,192407.0,185156.0,188910.0,470.540030,185915.0,198599.0,185915.0,False,True,False
2022-04-13,189000.0,195770.0,186200.0,194543.0,384.420730,185156.0,185915.0,185156.0,False,True,False
2022-04-14,194565.0,195581.0,194075.0,195581.0,18.766290,185156.0,185156.0,185156.0,True,True,True

In [181]:
BTC_BRL_df[BTC_BRL_df['Equal_1_3']!=True]

,Open,High,Low,Close,Volume,min_2cd_ant,min_2cd_ant_shift,min_2cd_ant_iloc,Equal_1_2,Equal_1_3,Equal_2_3
Date,,,,,,,,,,,
2020-10-13,63606.0,64059.0,46208.0,63921.0,2.876073,NaN,NaN,NA,False,False,False
2020-10-14,63920.0,64314.0,62677.0,64068.0,7.025460,NaN,NaN,NA,False,False,False

In [182]:
BTC_BRL_df[BTC_BRL_df['Equal_1_2']!=True]

,Open,High,Low,Close,Volume,min_2cd_ant,min_2cd_ant_shift,min_2cd_ant_iloc,Equal_1_2,Equal_1_3,Equal_2_3
Date,,,,,,,,,,,
2020-10-13,63606.0,64059.0,46208.0,63921.0,2.876073,NaN,NaN,NA,False,False,False
2020-10-14,63920.0,64314.0,62677.0,64068.0,7.025460,NaN,NaN,NA,False,False,False
2020-10-27,74348.0,79610.0,74324.0,78649.0,28.274538,72850.0,73230.0,72850.0,False,True,False
2020-11-03,78865.0,81769.0,77296.0,81400.0,23.562322,76771.0,79308.0,76771.0,False,True,False
2020-11-08,80907.0,85334.0,80295.0,84488.0,25.459966,78164.0,83145.0,78164.0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
2022-04-08,208145.0,210584.0,199846.0,200402.0,417.736820,203334.0,205000.0,203334.0,False,True,False
2022-04-09,200332.0,203045.0,199860.0,202899.0,140.514090,199846.0,203334.0,199846.0,False,True,False
2022-04-11,200065.0,201081.0,185915.0,187418.0,498.968770,198599.0,199860.0,198599.0,False,True,False
2022-04-12,187441.0,192407.0,185156.0,188910.0,470.540030,185915.0,198599.0,185915.0,False,True,False
2022-04-13,189000.0,195770.0,186200.0,194543.0,384.420730,185156.0,185915.0,185156.0,False,True,False

In [154]:
BTC_BRL_df.head(50)

,Open,High,Low,Close,Volume,min_2cd_ant,min_2cd_ant_shift,min_2cd_ant_iloc,Equal_1_2,Equal_1_3,Equal_2_3
Date,,,,,,,,,,,
2020-10-13,63606.0,64059.0,46208.0,63921.0,2.876073,NaN,NaN,NA,False,False,False
2020-10-14,63920.0,64314.0,62677.0,64068.0,7.025460,NaN,NaN,NA,False,False,False
2020-10-15,64068.0,65764.0,63505.0,65314.0,10.530935,46208.0,46208.0,46208.0,True,True,True
2020-10-16,65334.0,65560.0,63650.0,64750.0,9.181026,62677.0,62677.0,62677.0,True,True,True
2020-10-17,64600.0,65025.0,64418.0,64665.0,1.891715,63505.0,63505.0,63505.0,True,True,True
2020-10-18,64867.0,65667.0,64867.0,65667.0,5.881325,63650.0,63650.0,63650.0,True,True,True
2020-10-19,65772.0,66865.0,65112.0,66642.0,13.220203,64418.0,64418.0,64418.0,True,True,True
2020-10-20,66703.0,67873.0,66398.0,67574.0,12.395854,64867.0,64867.0,64867.0,True,True,True
2020-10-21,67585.0,74836.0,67542.0,72600.0,46.838386,65112.0,65112.0,65112.0,True,True,True
2020-10-22,72600.0,74336.0,71866.0,73136.0,28.977222,66398.0,66398.0,66398.0,True,True,True
2020-10-23,72856.0,73590.0,72139.0,73395.0,17.475821,67542.0,67542.0,67542.0,True,True,True
2020-10-24,73284.0,74656.0,73106.0,74377.0,12.191321,71866.0,71866.0,71866.0,True,True,True
2020-10-25,74370.0,75675.0,73230.0,73985.0,14.326097,72139.0,72139.0,72139.0,True,True,True
2020-10-26,73791.0,75437.0,72850.0,74396.0,26.827698,73106.0,73106.0,73106.0,True,True,True
2020-10-27,74348.0,79610.0,74324.0,78649.0,28.274538,72850.0,73230.0,72850.0,False,True,False
2020-10-28,78520.0,79884.0,75000.0,77186.0,29.312422,72850.0,72850.0,72850.0,True,True,True
2020-10-29,77145.0,79609.0,75776.0,78624.0,22.791691,74324.0,74324.0,74324.0,True,True,True
2020-10-30,78620.0,79800.0,76704.0,78820.0,24.466124,75000.0,75000.0,75000.0,True,True,True
2020-10-31,78804.0,81693.0,78158.0,80237.0,26.458667,75776.0,75776.0,75776.0,True,True,True
2020-11-01,80132.0,80683.0,79308.0,79875.0,8.675342,76704.0,76704.0,76704.0,True,True,True
2020-11-02,79992.0,80346.0,76771.0,78730.0,11.350811,78158.0,78158.0,78158.0,True,True,True
2020-11-03,78865.0,81769.0,77296.0,81400.0,23.562322,76771.0,79308.0,76771.0,False,True,False
2020-11-04,81511.0,81733.0,78800.0,81197.0,25.915073,76771.0,76771.0,76771.0,True,True,True
2020-11-05,81191.0,88229.0,80929.0,87587.0,57.831970,77296.0,77296.0,77296.0,True,True,True
2020-11-06,87644.0,89646.0,83145.0,85124.0,48.722777,78800.0,78800.0,78800.0,True,True,True
2020-11-07,84981.0,85962.0,78164.0,80929.0,55.008206,80929.0,80929.0,80929.0,True,True,True
2020-11-08,80907.0,85334.0,80295.0,84488.0,25.459966,78164.0,83145.0,78164.0,False,True,False
2020-11-09,84351.0,86256.0,80439.0,83858.0,64.395561,78164.0,78164.0,78164.0,True,True,True
2020-11-10,83821.0,88000.0,83009.0,85337.0,64.760007,80295.0,80295.0,80295.0,True,True,True
2020-11-11,85483.0,89300.0,84817.0,86315.0,106.969211,80439.0,80439.0,80439.0,True,True,True
2020-11-12,86379.0,89991.0,85040.0,89292.0,54.693562,83009.0,83009.0,83009.0,True,True,True
2020-11-13,89341.0,90236.0,87595.0,90032.0,55.072808,84817.0,84817.0,84817.0,True,True,True
2020-11-14,89966.0,90050.0,87325.0,88932.0,19.202403,85040.0,85040.0,85040.0,True,True,True
2020-11-15,88947.0,89267.0,87382.0,88394.0,10.783433,87325.0,87595.0,87325.0,False,True,False
2020-11-16,88231.0,92182.0,87787.0,90963.0,39.068688,87325.0,87325.0,87325.0,True,True,True
2020-11-17,91030.0,96439.0,90250.0,94965.0,87.253409,87382.0,87382.0,87382.0,True,True,True
2020-11-18,94925.0,99151.0,92000.0,96031.0,110.753420,87787.0,87787.0,87787.0,True,True,True
2020-11-19,96221.0,97500.0,93865.0,95655.0,48.712126,90250.0,90250.0,90250.0,True,True,True
2020-11-20,95670.0,101407.0,95268.0,100700.0,48.565317,92000.0,92000.0,92000.0,True,True,True
2020-11-21,100700.0,101935.0,99445.0,100870.0,21.162159,93865.0,93865.0,93865.0,True,True,True
2020-11-22,100862.0,101409.0,96230.0,100074.0,28.566044,95268.0,95268.0,95268.0,True,True,True
2020-11-23,99941.0,102000.0,98181.0,100572.0,46.397910,96230.0,99445.0,96230.0,False,True,False
2020-11-24,100553.0,106089.0,98750.0,104504.0,84.170582,96230.0,96230.0,96230.0,True,True,True
2020-11-25,104469.0,105426.0,99999.0,100805.0,75.893256,98181.0,98181.0,98181.0,True,True,True
2020-11-26,100599.0,101841.0,80000.0,93482.0,212.303425,98750.0,98750.0,98750.0,True,True,True
2020-11-27,93482.0,94929.0,89003.0,92867.0,114.060083,80000.0,99999.0,80000.0,False,True,False
2020-11-28,92912.0,96550.0,91307.0,95887.0,32.517919,80000.0,80000.0,80000.0,True,True,True
2020-11-29,95971.0,99000.0,94942.0,98066.0,26.267791,89003.0,89003.0,89003.0,True,True,True
2020-11-30,98200.0,106251.0,98200.0,104999.0,82.114522,91307.0,91307.0,91307.0,True,True,True
2020-12-01,104932.0,105500.0,96913.0,99124.0,101.918485,94942.0,94942.0,94942.0,True,True,True

In [ ]:
min_2cd_ant_iloc = BTC_BRL_df['Low'].shift(2)
BTC_BRL_df['min_2cd_ant_iloc'] = min_2cd_ant_iloc
BTC_BRL_df.head()

In [115]:
## Máximas dos próximos 2 candles
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=-2)
min_2cd_ant_indexer = BTC_BRL_df['Low'].rolling(window=indexer).min()
min_2cd_ant_indexer

Date
2020-10-13         NaN
2020-10-14         NaN
2020-10-15     63505.0
2020-10-16     63650.0
2020-10-17     64418.0
                ...
2022-04-10    185156.0
2022-04-11    185156.0
2022-04-12    185156.0
2022-04-13    186200.0
2022-04-14    194075.0
Name: Low, Length: 549, dtype: float64

In [ ]:
## Usando o for e iloc

lista_min_2cd_ant = []

In [ ]:
Regra1 =  btc_df['low'] < btc_df['min_2cd_ant']
btc_df['Regra1'] = Regra1
btc_df.head(10)

                open      high       low     close  min_2cd_ant  Regra1
date
2021-01-01  152056.0  154167.0  150911.0  153480.0          NaN   False
2021-01-02  153478.0  173900.0  152171.0  168784.0          NaN   False
2021-01-03  168885.0  180925.0  167897.0  173503.0     150911.0   False
2021-01-04  173504.0  175981.0  150000.0  169820.0     152171.0    True
2021-01-05  169825.0  182966.0  159769.0  179972.0     150000.0   False
2021-01-06  179990.0  197555.0  177210.0  196635.0     150000.0   False
2021-01-07  196752.0  222813.0  194600.0  215874.0     159769.0   False
2021-01-08  216160.0  228045.0  200150.0  222915.0     177210.0   False
2021-01-09  223113.0  225333.0  213593.0  220612.0     194600.0   False
2021-01-10  220504.0  224900.0  188500.0  209390.0     200150.0    True

In [ ]:
fig = make_subplots(rows=1, cols=1)

data_range_btc_df = pd.date_range(start='2021-01-01',end='2021-01-04')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

fig.add_trace(go.Candlestick(name='Bitcoin_BRL', x=btc_df_index_range.index, open=btc_df_index_range['open'], high = btc_df_index_range['high'], low=btc_df_index_range['low'], close=btc_df_index_range['close'],showlegend=True), row=1,col=1)
fig.update_yaxes(title_text="<b> Preço Bitcoin (R$)", row=1, col=1)

fig.update_layout(xaxis_rangeslider_visible=False,legend=dict(orientation="h",xanchor="right",x=1,yanchor="bottom",y=1.1),title_text='<b>Regra 1 (low 0 < low 1,2) = True' ,width=1000 ,height=500)
fig.show()

**Regra 2:** Close 0 > Close 1

In [ ]:
## Fechamento do candle anterior
fech_cd_ant = btc_df['close'].rolling(window=1,closed='left').min()
btc_df['fech_cd_ant'] = fech_cd_ant
btc_df.head()

                open      high       low  ...  min_2cd_ant  Regra1  fech_cd_ant
date                                      ...
2021-01-01  152056.0  154167.0  150911.0  ...          NaN   False          NaN
2021-01-02  153478.0  173900.0  152171.0  ...          NaN   False     153480.0
2021-01-03  168885.0  180925.0  167897.0  ...     150911.0   False     168784.0
2021-01-04  173504.0  175981.0  150000.0  ...     152171.0    True     173503.0
2021-01-05  169825.0  182966.0  159769.0  ...     150000.0   False     169820.0

[5 rows x 7 columns]

In [ ]:
Regra2 =  btc_df['close'] > btc_df['fech_cd_ant']
btc_df['Regra2'] = Regra2
btc_df.head()

                open      high       low  ...  Regra1  fech_cd_ant  Regra2
date                                      ...
2021-01-01  152056.0  154167.0  150911.0  ...   False          NaN   False
2021-01-02  153478.0  173900.0  152171.0  ...   False     153480.0    True
2021-01-03  168885.0  180925.0  167897.0  ...   False     168784.0    True
2021-01-04  173504.0  175981.0  150000.0  ...    True     173503.0   False
2021-01-05  169825.0  182966.0  159769.0  ...   False     169820.0    True

[5 rows x 8 columns]

In [ ]:
fig = make_subplots(rows=1, cols=1)

data_range_btc_df = pd.date_range(start='2021-01-01',end='2021-01-04')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

fig.add_trace(go.Candlestick(name='Bitcoin_BRL', x=btc_df_index_range.index, open=btc_df_index_range['open'], high = btc_df_index_range['high'], low=btc_df_index_range['low'], close=btc_df_index_range['close'],showlegend=True), row=1,col=1)
fig.update_yaxes(title_text="<b> Preço Bitcoin (R$)", row=1, col=1)

fig.update_layout(xaxis_rangeslider_visible=False,legend=dict(orientation="h",xanchor="right",x=1,yanchor="bottom",y=1.1),title_text=('<b>Regra 2 (close 0 > close 1) = False') ,width=1000 ,height=500)

fig.show()

In [ ]:
## Se Regra 1 e 2 forem verdadeiras → sinal de compra = True
sinal_compra = btc_df['Regra1'] * btc_df['Regra2']
btc_df['sinal_compra'] = sinal_compra
btc_df.head(25)

                open      high       low  ...  fech_cd_ant  Regra2  sinal_compra
date                                      ...
2021-01-01  152056.0  154167.0  150911.0  ...          NaN   False         False
2021-01-02  153478.0  173900.0  152171.0  ...     153480.0    True         False
2021-01-03  168885.0  180925.0  167897.0  ...     168784.0    True         False
2021-01-04  173504.0  175981.0  150000.0  ...     173503.0   False         False
2021-01-05  169825.0  182966.0  159769.0  ...     169820.0    True         False
2021-01-06  179990.0  197555.0  177210.0  ...     179972.0    True         False
2021-01-07  196752.0  222813.0  194600.0  ...     196635.0    True         False
2021-01-08  216160.0  228045.0  200150.0  ...     215874.0    True         False
2021-01-09  223113.0  225333.0  213593.0  ...     222915.0   False         False
2021-01-10  220504.0  224900.0  188500.0  ...     220612.0   False         False
2021-01-11  209415.0  209822.0  168112.0  ...     209390.0   False         False
2021-01-12  199160.0  203999.0  180375.0  ...     199020.0   False         False
2021-01-13  183868.0  200600.0  177000.0  ...     184137.0    True         False
2021-01-14  198827.0  211899.0  196299.0  ...     198819.0    True         False
2021-01-15  205900.0  207684.0  184563.0  ...     206134.0   False         False
2021-01-16  197757.0  202124.0  190633.0  ...     197976.0   False         False
2021-01-17  194236.0  196869.0  185000.0  ...     194270.0   False         False
2021-01-18  191912.0  198600.0  186819.0  ...     191912.0    True         False
2021-01-19  194691.0  201000.0  193021.0  ...     194756.0   False         False
2021-01-20  193797.0  196125.0  180000.0  ...     193900.0   False         False
2021-01-21  189203.0  189908.0  163651.0  ...     189367.0   False         False
2021-01-22  167340.0  186000.0  155000.0  ...     167696.0    True          True
2021-01-23  181219.0  183206.0  174000.0  ...     181268.0   False         False
2021-01-24  177289.0  181483.0  171438.0  ...     177319.0    True         False
2021-01-25  177621.0  191348.0  176000.0  ...     177459.0    True         False

[25 rows x 9 columns]

In [ ]:
## Filtro: apenas candles que representaram sinal de compra
sinal_compra_df = btc_df[btc_df.sinal_compra == True]
sinal_compra_df

                open      high       low  ...  fech_cd_ant  Regra2  sinal_compra
date                                      ...
2021-01-22  167340.0  186000.0  155000.0  ...     167696.0    True          True
2021-03-05  277237.0  283451.0  266390.0  ...     277237.0    True          True
2021-03-16  317383.0  322436.0  305262.0  ...     317705.0    True          True
2021-03-23  303155.0  310000.0  296252.0  ...     303155.0    True          True
2021-04-04  332809.0  338597.0  328095.0  ...     332818.0    True          True
2021-05-30  182731.0  192127.0  176727.0  ...     182653.0    True          True
2021-06-20  183146.0  186220.0  172850.0  ...     183116.0    True          True
2021-06-22  160890.0  169364.0  145000.0  ...     160917.0    True          True
2021-06-26  158466.0  163250.0  151151.0  ...     158467.0    True          True
2021-07-30  204489.0  220513.0  196501.0  ...     204388.0    True          True
2021-08-04  200087.0  208797.0  196700.0  ...     200032.0    True          True
2021-08-05  207081.0  216025.0  194836.0  ...     206982.0    True          True
2021-08-18  238868.0  246890.0  236712.0  ...     239281.0    True          True
2021-08-25  253287.0  259475.0  250397.0  ...     253289.0    True          True
2021-09-01  245634.0  254560.0  242717.0  ...     245700.0    True          True
2021-09-29  224358.0  231450.0  223094.0  ...     224191.0    True          True
2021-10-23  345006.0  351244.0  340000.0  ...     344913.0    True          True
2021-10-28  329076.0  353296.0  326742.0  ...     328916.0    True          True
2021-11-06  342834.0  346195.0  337858.0  ...     342868.0    True          True
2021-11-17  335435.0  339998.0  327052.0  ...     335535.0    True          True
2021-11-19  321252.0  329492.0  314003.0  ...     321252.0    True          True
2021-11-23  319149.0  328734.0  314000.0  ...     319150.0    True          True
2021-12-11  267706.0  283000.0  265000.0  ...     267382.0    True          True
2021-12-18  262968.0  269499.0  259301.0  ...     262968.0    True          True
2021-12-26  288492.0  292796.0  283013.0  ...     288356.0    True          True

[25 rows x 9 columns]

In [ ]:
## Variavel interessante: Qts entradas considerando este ativo, neste intervalo e neste timeframe?
n_sinal_compra_df = len(sinal_compra_df)
n_sinal_compra_df

25

In [ ]:
## Visualização usando um data range
data_range_btc_df = pd.date_range(start='2021-03-01',end='2021-03-31')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

                open      high       low  ...  fech_cd_ant  Regra2  sinal_compra
date                                      ...
2021-03-01  257538.0  282000.0  256447.0  ...     257551.0    True         False
2021-03-02  281490.0  284121.0  269332.0  ...     281400.0   False         False
2021-03-03  277000.0  299600.0  275353.0  ...     277000.0    True         False
2021-03-04  285401.0  293100.0  271140.0  ...     285401.0   False         False
2021-03-05  277237.0  283451.0  266390.0  ...     277237.0    True          True
2021-03-06  279696.0  282000.0  271285.0  ...     279491.0    True         False
2021-03-07  280000.0  291899.0  279950.0  ...     279999.0    True         False
2021-03-08  289458.0  303500.0  280970.0  ...     288621.0    True         False
2021-03-09  303500.0  319500.0  300665.0  ...     303500.0    True         False
2021-03-10  318210.0  327886.0  308500.0  ...     318596.0    True         False
2021-03-11  319982.0  323750.0  312142.0  ...     319982.0    True         False
2021-03-12  322300.0  323600.0  310245.0  ...     322079.0   False         False
2021-03-13  320847.0  346263.0  317000.0  ...     320848.0    True         False
2021-03-14  343470.0  345300.0  333861.0  ...     343198.0   False         False
2021-03-15  333880.0  344150.0  313000.0  ...     333982.0   False         False
2021-03-16  317383.0  322436.0  305262.0  ...     317705.0    True          True
2021-03-17  322222.0  331244.0  309832.0  ...     322326.0    True         False
2021-03-18  330772.0  335000.0  320405.0  ...     330772.0   False         False
2021-03-19  324342.0  330573.0  317871.0  ...     324342.0   False         False
2021-03-20  323256.0  331000.0  322200.0  ...     323267.0    True         False
2021-03-21  323700.0  326996.0  313100.0  ...     323803.0   False         False
2021-03-22  321000.0  325549.0  301502.0  ...     321000.0   False         False
2021-03-23  303155.0  310000.0  296252.0  ...     303155.0    True          True
2021-03-24  304193.0  318778.0  295002.0  ...     304195.0   False         False
2021-03-25  299563.0  302978.0  288502.0  ...     299572.0   False         False
2021-03-26  293860.0  318604.0  293200.0  ...     293437.0    True         False
2021-03-27  318575.0  325000.0  312901.0  ...     318579.0    True         False
2021-03-28  321637.0  324346.0  316009.0  ...     321764.0   False         False
2021-03-29  321242.0  337900.0  316296.0  ...     321039.0    True         False
2021-03-30  332501.0  341768.0  330323.0  ...     332768.0    True         False
2021-03-31  339499.0  343806.0  330100.0  ...     339500.0   False         False

[31 rows x 9 columns]

In [ ]:
## Geral 
fig = make_subplots(rows=1, cols=2)

## Figura 1
data_range_btc_df = pd.date_range(start='2021-03-01',end='2021-03-31')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

fig.add_trace(go.Candlestick(name='Bitcoin_BRL', x=btc_df_index_range.index, open=btc_df_index_range['open'], high = btc_df_index_range['high'], low=btc_df_index_range['low'], close=btc_df_index_range['close']), row=1,col=1)
fig.update_yaxes(title_text="<b> Preço Bitcoin (R$)",row=1, col=1)
fig.add_vrect(x0='2021-03-02 12:00', x1='2021-03-07 15:00', fillcolor="green", opacity=0.25, line_width=0,row=1, col=1)
fig.add_trace(go.Scatter(x=['2021-03-05'],y=[330000],mode="text",text="<b>Zoom",textposition="top center",showlegend=False),row=1, col=1)

## Figura 2
data_range_btc_df = pd.date_range(start='2021-03-03',end='2021-03-07')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

fig.add_trace(go.Candlestick(name='Bitcoin_BRL', x=btc_df_index_range.index, open=btc_df_index_range['open'], high = btc_df_index_range['high'], low=btc_df_index_range['low'], close=btc_df_index_range['close'],showlegend=False), row=1,col=2)
fig.update_yaxes(title_text="<b> Preço Bitcoin (R$)", row=1, col=2)
fig.add_annotation(x='2021-03-05',y=270000, xref="x",yref="y",text="<b>Candle_Sinalizador",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="center",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=2)
fig.add_annotation(x='2021-03-05',y=283452, xref="x",yref="y",text="<b>Compra Max + 1",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="right",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=2)
fig.add_annotation(x='2021-03-07',y=283452, xref="x",yref="y",text="<b>Compra ativada",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="left",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=2)
fig.add_trace(go.Scatter(x=['2021-03-04 20:00','2021-03-07 10:00'],y=[283451,283451,283451], mode="lines+text", name="Preço entrada compra",
                         line = dict(color='green', width=2, dash='dash')),row=1, col=2)

## Geral
fig.update_layout(xaxis_rangeslider_visible=False,xaxis2_rangeslider_visible=False,legend=dict(orientation="h",xanchor="right",x=1,yanchor="bottom",y=1.1),title_text='Sinal Compra PFR' ,width=1000 ,height=500)

fig.show()

In [ ]:
## Figura 2 apenas
fig = make_subplots(rows=1, cols=1)

data_range_btc_df = pd.date_range(start='2021-03-03',end='2021-03-07')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

fig.add_trace(go.Candlestick(name='Bitcoin_BRL', x=btc_df_index_range.index, open=btc_df_index_range['open'], high = btc_df_index_range['high'], low=btc_df_index_range['low'], close=btc_df_index_range['close'],showlegend=True), row=1,col=1)
fig.update_yaxes(title_text="<b> Preço Bitcoin (R$)", row=1, col=1)
fig.add_annotation(x='2021-03-05',y=270000, xref="x",yref="y",text="<b>Candle_Sinalizador",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="center",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)
fig.add_annotation(x='2021-03-05',y=283452, xref="x",yref="y",text="<b>Compra Max + 1",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="right",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)
fig.add_annotation(x='2021-03-07',y=283452, xref="x",yref="y",text="<b>Compra ativada",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="left",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)
fig.add_trace(go.Scatter(x=['2021-03-04 20:00','2021-03-07 10:00'],y=[283451,283451,283451], mode="lines+text", name="Preço entrada compra",
                         line = dict(color='green', width=2, dash='dash')),row=1, col=1)

## Geral
fig.update_layout(xaxis_rangeslider_visible=False,legend=dict(orientation="h",xanchor="right",x=1,yanchor="bottom",y=1.1),title_text='Sinal Compra PFR' ,width=1000 ,height=500)

fig.show()

In [ ]:
## O que aconteceu depois?

fig = make_subplots(rows=1, cols=1)

data_range_btc_df = pd.date_range(start='2021-03-03',end='2021-03-12')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

fig.add_trace(go.Candlestick(name='Bitcoin_BRL', x=btc_df_index_range.index, open=btc_df_index_range['open'], high = btc_df_index_range['high'], low=btc_df_index_range['low'], close=btc_df_index_range['close'],showlegend=True), row=1,col=1)
fig.update_yaxes(title_text="<b> Preço Bitcoin (R$)", row=1, col=1)
fig.add_annotation(x='2021-03-05',y=270000, xref="x",yref="y",text="<b>Candle_Sinalizador",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="center",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)
fig.add_annotation(x='2021-03-05',y=283452, xref="x",yref="y",text="<b>Compra Max + 1",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="right",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)
fig.add_annotation(x='2021-03-07',y=283452, xref="x",yref="y",text="<b>Compra ativada",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="left",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)
fig.add_trace(go.Scatter(x=['2021-03-04 20:00','2021-03-07 10:00'],y=[283451,283451,283451], mode="lines+text", name="Preço entrada compra",
                         line = dict(color='green', width=2, dash='dash')),row=1, col=1)

## Geral
fig.update_layout(xaxis_rangeslider_visible=False,legend=dict(orientation="h",xanchor="right",x=1,yanchor="bottom",y=1.1),title_text='Sinal Compra PFR' ,width=1000 ,height=500)

fig.show()

## **3.3. Entradas de COMPRA executadas**

Se Preco > High (candle sinalizador) + Min_Incr = Compra executada<p>
PS: Definiremos que o período máx para acontecer são 2 candles

In [ ]:
## Criar uma coluna para informar se entrei ou nao na operação. Daremos uma janela de 2 candles no máx para entrar.
## Para células posteriores, usar o FixedForwardWindowIndexer

## Máximas dos próximos 2 candles
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=2)
max_cd_sig_prox = btc_df['high'].rolling(window=indexer).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=3)
max_cd_sig_prox2 = btc_df['high'].rolling(window=indexer).max()
btc_df['max_cd_sig_prox'] = max_cd_sig_prox
btc_df['max_cd_sig_prox2'] = max_cd_sig_prox2
btc_df.head()

                open      high  ...  max_cd_sig_prox  max_cd_sig_prox2
date                            ...
2021-01-01  152056.0  154167.0  ...         173900.0          180925.0
2021-01-02  153478.0  173900.0  ...         180925.0          180925.0
2021-01-03  168885.0  180925.0  ...         180925.0          182966.0
2021-01-04  173504.0  175981.0  ...         182966.0          197555.0
2021-01-05  169825.0  182966.0  ...         197555.0          222813.0

[5 rows x 11 columns]

In [ ]:
## Entrada compra ativada? Lembrando que tick_min foi definido em params
btc_df['Compra_ativ_1cd'] = (btc_df['max_cd_sig_prox'] > (btc_df['high']+1*tick_min)) *  btc_df['sinal_compra']
btc_df['Compra_ativ_2cd'] = (btc_df['max_cd_sig_prox2'] > (btc_df['high']+1*tick_min)) *  btc_df['sinal_compra']
btc_df.head(25)

                open      high  ...  Compra_ativ_1cd  Compra_ativ_2cd
date                            ...
2021-01-01  152056.0  154167.0  ...            False            False
2021-01-02  153478.0  173900.0  ...            False            False
2021-01-03  168885.0  180925.0  ...            False            False
2021-01-04  173504.0  175981.0  ...            False            False
2021-01-05  169825.0  182966.0  ...            False            False
2021-01-06  179990.0  197555.0  ...            False            False
2021-01-07  196752.0  222813.0  ...            False            False
2021-01-08  216160.0  228045.0  ...            False            False
2021-01-09  223113.0  225333.0  ...            False            False
2021-01-10  220504.0  224900.0  ...            False            False
2021-01-11  209415.0  209822.0  ...            False            False
2021-01-12  199160.0  203999.0  ...            False            False
2021-01-13  183868.0  200600.0  ...            False            False
2021-01-14  198827.0  211899.0  ...            False            False
2021-01-15  205900.0  207684.0  ...            False            False
2021-01-16  197757.0  202124.0  ...            False            False
2021-01-17  194236.0  196869.0  ...            False            False
2021-01-18  191912.0  198600.0  ...            False            False
2021-01-19  194691.0  201000.0  ...            False            False
2021-01-20  193797.0  196125.0  ...            False            False
2021-01-21  189203.0  189908.0  ...            False            False
2021-01-22  167340.0  186000.0  ...            False            False
2021-01-23  181219.0  183206.0  ...            False            False
2021-01-24  177289.0  181483.0  ...            False            False
2021-01-25  177621.0  191348.0  ...            False            False

[25 rows x 13 columns]

In [ ]:
data_range_btc_df = pd.date_range(start='2021-01-19',end='2021-01-24')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

fig = make_subplots(rows=1, cols=1)

fig.add_trace(go.Candlestick(name='Bitcoin_BRL', x=btc_df_index_range.index, open=btc_df_index_range['open'], high = btc_df_index_range['high'], low=btc_df_index_range['low'], close=btc_df_index_range['close'],showlegend=True), row=1,col=1)
fig.update_yaxes(title_text="<b> Preço Bitcoin (R$)", row=1, col=1)

fig.add_annotation(x='2021-01-22',y=160000, xref="x",yref="y",text="<b>Candle_Sinalizador",showarrow=True,font=dict(family="Courier New, monospace",size=16,color="black"),align="center",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black")
fig.add_annotation(x='2021-01-22',y=186001, xref="x",yref="y",text="<b>Compra Max + 1",showarrow=True,font=dict(family="Courier New, monospace",size=16,color="black"),align="right",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black")
fig.add_trace(go.Scatter(x=['2021-01-21 20:00','2021-01-24 10:00'],y=[186001,186001,186001], mode="lines+text", name="Preço entrada compra",
                         line = dict(color='green', width=2, dash='dash')),row=1, col=1)

fig.add_annotation(x='2021-01-24',y=186001, xref="x",yref="y",text="<b>Compra NÃO ativada",showarrow=True,font=dict(family="Courier New, monospace",size=12,color="black"),align="left",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)

fig.update_layout(xaxis_rangeslider_visible=False, title_text='Sinal Compra PFR',width=800 ,height=800)
fig.show()

In [ ]:
data_range_btc_df = pd.date_range(start='2021-01-19',end='2021-01-31')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

fig = make_subplots(rows=1, cols=1)

fig.add_trace(go.Candlestick(name='Bitcoin_BRL', x=btc_df_index_range.index, open=btc_df_index_range['open'], high = btc_df_index_range['high'], low=btc_df_index_range['low'], close=btc_df_index_range['close'],showlegend=True), row=1,col=1)
fig.update_yaxes(title_text="<b> Preço Bitcoin (R$)", row=1, col=1)

fig.add_annotation(x='2021-01-22',y=160000, xref="x",yref="y",text="<b>Candle_Sinalizador",showarrow=True,font=dict(family="Courier New, monospace",size=10,color="black"),align="center",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black")
fig.add_annotation(x='2021-01-22',y=186001, xref="x",yref="y",text="<b>Compra Max + 1",showarrow=True,font=dict(family="Courier New, monospace",size=10,color="black"),align="right",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black")
fig.add_trace(go.Scatter(x=['2021-01-21 20:00','2021-01-24 10:00'],y=[186001,186001,186001], mode="lines+text", name="Preço entrada compra",
                         line = dict(color='green', width=2, dash='dash')),row=1, col=1)

fig.add_annotation(x='2021-01-24',y=186001, xref="x",yref="y",text="<b>Compra NÃO ativada",showarrow=True,font=dict(family="Courier New, monospace",size=10,color="black"),align="left",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)

fig.update_layout(xaxis_rangeslider_visible=False, title_text='Sinal Compra PFR',width=800 ,height=800)
fig.show()

In [ ]:
## Filtro: apenas candles que representaram sinal de compra (apresentado acima mas agora com entrada ativada)
sinal_compra_df = btc_df[btc_df.sinal_compra == True]
sinal_compra_df

                open      high  ...  Compra_ativ_1cd  Compra_ativ_2cd
date                            ...
2021-01-22  167340.0  186000.0  ...            False            False
2021-03-05  277237.0  283451.0  ...            False             True
2021-03-16  317383.0  322436.0  ...             True             True
2021-03-23  303155.0  310000.0  ...             True             True
2021-04-04  332809.0  338597.0  ...             True             True
2021-05-30  182731.0  192127.0  ...             True             True
2021-06-20  183146.0  186220.0  ...            False            False
2021-06-22  160890.0  169364.0  ...             True             True
2021-06-26  158466.0  163250.0  ...             True             True
2021-07-30  204489.0  220513.0  ...             True             True
2021-08-04  200087.0  208797.0  ...             True             True
2021-08-05  207081.0  216025.0  ...             True             True
2021-08-18  238868.0  246890.0  ...             True             True
2021-08-25  253287.0  259475.0  ...             True             True
2021-09-01  245634.0  254560.0  ...             True             True
2021-09-29  224358.0  231450.0  ...             True             True
2021-10-23  345006.0  351244.0  ...            False             True
2021-10-28  329076.0  353296.0  ...             True             True
2021-11-06  342834.0  346195.0  ...             True             True
2021-11-17  335435.0  339998.0  ...             True             True
2021-11-19  321252.0  329492.0  ...             True             True
2021-11-23  319149.0  328734.0  ...            False             True
2021-12-11  267706.0  283000.0  ...             True             True
2021-12-18  262968.0  269499.0  ...             True             True
2021-12-26  288492.0  292796.0  ...             True             True

[25 rows x 13 columns]

In [ ]:
## Filtro: apenas candles que representaram sinal de compra (apresentado acima mas agora com entrada ativada)
compras_ativadas_1cd_df = sinal_compra_df[sinal_compra_df.Compra_ativ_1cd == True]
compras_ativadas_2cd_df = sinal_compra_df[sinal_compra_df.Compra_ativ_2cd == True]
print(len(compras_ativadas_1cd_df))
len(compras_ativadas_2cd_df)

20

23

## **3.4. Definindo os alvos gain x stop loss**

candle sinalizador = cdsig<p>
Alvo_Fibonacci = 1.61

*Stop loss*:<p>
Preco < Low_cdsig - Min_Incr -> Sell to Cover Stop<p>

*Alvos Gain* (2):<p>
Gain1 = Se Preco > (Max_cdsig + Min_Incr) + Amplitude_cdsig = Sell to Cover Limit<p>
Gain2 = Se Preco > (Max_cdsig + Min_Incr) + (Amplitude_cdsig * 1.61) = Sell to Cover Limit

In [ ]:
## Amplitude (max - min) do candle sinalizador
btc_df['range'] = btc_df['high']-btc_df['low']

## Preço do Stop loss: Min cd sinal - tick_min

btc_df['stop_loss'] = btc_df['low'] - tick_min

## Preco Alvo Gain: Max cd sinal + 1 + Range candle sinal

btc_df['alvo_gain1'] = btc_df['high'] + tick_min + btc_df['range']
btc_df['alvo_gain2'] = btc_df['high'] + tick_min + (Alvo_Fibonacci * btc_df['range'])

btc_df

                open      high       low  ...  stop_loss  alvo_gain1  alvo_gain2
date                                      ...
2021-01-01  152056.0  154167.0  150911.0  ...   150910.0    157424.0   159410.16
2021-01-02  153478.0  173900.0  152171.0  ...   152170.0    195630.0   208884.69
2021-01-03  168885.0  180925.0  167897.0  ...   167896.0    193954.0   201901.08
2021-01-04  173504.0  175981.0  150000.0  ...   149999.0    201963.0   217811.41
2021-01-05  169825.0  182966.0  159769.0  ...   159768.0    206164.0   220314.17
...              ...       ...       ...  ...        ...         ...         ...
2021-12-27  290189.0  295785.0  287534.0  ...   287533.0    304037.0   309070.11
2021-12-28  288339.0  288339.0  269171.0  ...   269170.0    307508.0   319200.48
2021-12-29  270357.0  274941.0  264773.0  ...   264772.0    285110.0   291312.48
2021-12-30  266975.0  280000.0  263500.0  ...   263499.0    296501.0   306566.00
2021-12-31  265634.0  273059.0  257721.0  ...   257720.0    288398.0   297754.18

[365 rows x 17 columns]

## **3.5. Verificar onde o preço chegou primeiro: stop loss ou gain?**

In [ ]:
## Primeiro devo calcular a min e max dos 'próximos candles' (lembrando que inclui o candle sinalizador)
## Entretanto, dependendo do tempo da operação pode ficar chato fazer na mão (além de grande risco de erros)

indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=2)
min_cd_prox1 = btc_df['low'].rolling(window=indexer).min()
max_cd_prox1 = btc_df['high'].rolling(window=indexer).max()

indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=3)
min_cd_prox2 = btc_df['low'].rolling(window=indexer).min()
max_cd_prox2 = btc_df['high'].rolling(window=indexer).max()

<img src="https://s3.manualzz.com/store/data/035682191_1-cb12413719b59b4f0190c1355bbe02ad-360x466.png" width="300">

In [ ]:
## Aqui você pode determinar até quantos candles ficará na operação. Aqui depende mt do setup. Alguns encerram por tempo, outros so qd chegar nos alvos...
## Copiar o outputr e colar na linha de código abaixo

for i in range(1,11):
  print('indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=',i+1,')',sep='')
  print('btc_df["min_cd_prox',i,'"] = btc_df["low"].rolling(window=',i+1,').min()',sep='')
  print('btc_df["max_cd_prox',i,'"] = btc_df["high"].rolling(window=',i+1,').max()',sep='')

indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=2)
btc_df["min_cd_prox1"] = btc_df["low"].rolling(window=2).min()
btc_df["max_cd_prox1"] = btc_df["high"].rolling(window=2).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=3)
btc_df["min_cd_prox2"] = btc_df["low"].rolling(window=3).min()
btc_df["max_cd_prox2"] = btc_df["high"].rolling(window=3).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=4)
btc_df["min_cd_prox3"] = btc_df["low"].rolling(window=4).min()
btc_df["max_cd_prox3"] = btc_df["high"].rolling(window=4).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=5)
btc_df["min_cd_prox4"] = btc_df["low"].rolling(window=5).min()
btc_df["max_cd_prox4"] = btc_df["high"].rolling(window=5).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=6)
btc_df["min_cd_prox5"] = btc_df["low"].rolling(window=6).min()
btc_df["max_cd_prox5"] = btc_df["high"].rolling(window=6).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=7)
btc_df["min_cd_prox6"] = btc_df["low"].rolling(window=7).min()
btc_df["max_cd_prox6"] = btc_df["high"].rolling(window=7).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=8)
btc_df["min_cd_prox7"] = btc_df["low"].rolling(window=8).min()
btc_df["max_cd_prox7"] = btc_df["high"].rolling(window=8).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=9)
btc_df["min_cd_prox8"] = btc_df["low"].rolling(window=9).min()
btc_df["max_cd_prox8"] = btc_df["high"].rolling(window=9).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=10)
btc_df["min_cd_prox9"] = btc_df["low"].rolling(window=10).min()
btc_df["max_cd_prox9"] = btc_df["high"].rolling(window=10).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=11)
btc_df["min_cd_prox10"] = btc_df["low"].rolling(window=11).min()
btc_df["max_cd_prox10"] = btc_df["high"].rolling(window=11).max()

In [ ]:
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=2)
btc_df["min_cd_prox1"] = btc_df["low"].rolling(window=2).min()
btc_df["max_cd_prox1"] = btc_df["high"].rolling(window=2).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=3)
btc_df["min_cd_prox2"] = btc_df["low"].rolling(window=3).min()
btc_df["max_cd_prox2"] = btc_df["high"].rolling(window=3).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=4)
btc_df["min_cd_prox3"] = btc_df["low"].rolling(window=4).min()
btc_df["max_cd_prox3"] = btc_df["high"].rolling(window=4).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=5)
btc_df["min_cd_prox4"] = btc_df["low"].rolling(window=5).min()
btc_df["max_cd_prox4"] = btc_df["high"].rolling(window=5).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=6)
btc_df["min_cd_prox5"] = btc_df["low"].rolling(window=6).min()
btc_df["max_cd_prox5"] = btc_df["high"].rolling(window=6).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=7)
btc_df["min_cd_prox6"] = btc_df["low"].rolling(window=7).min()
btc_df["max_cd_prox6"] = btc_df["high"].rolling(window=7).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=8)
btc_df["min_cd_prox7"] = btc_df["low"].rolling(window=8).min()
btc_df["max_cd_prox7"] = btc_df["high"].rolling(window=8).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=9)
btc_df["min_cd_prox8"] = btc_df["low"].rolling(window=9).min()
btc_df["max_cd_prox8"] = btc_df["high"].rolling(window=9).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=10)
btc_df["min_cd_prox9"] = btc_df["low"].rolling(window=10).min()
btc_df["max_cd_prox9"] = btc_df["high"].rolling(window=10).max()
indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=11)
btc_df["min_cd_prox10"] = btc_df["low"].rolling(window=11).min()
btc_df["max_cd_prox10"] = btc_df["high"].rolling(window=11).max()

In [ ]:
print(len(btc_df.columns))
btc_df.columns

37

Index(['open', 'high', 'low', 'close', 'min_2cd_ant', 'Regra1', 'fech_cd_ant',
       'Regra2', 'sinal_compra', 'max_cd_sig_prox', 'max_cd_sig_prox2',
       'Compra_ativ_1cd', 'Compra_ativ_2cd', 'range', 'stop_loss',
       'alvo_gain1', 'alvo_gain2', 'min_cd_prox1', 'max_cd_prox1',
       'min_cd_prox2', 'max_cd_prox2', 'min_cd_prox3', 'max_cd_prox3',
       'min_cd_prox4', 'max_cd_prox4', 'min_cd_prox5', 'max_cd_prox5',
       'min_cd_prox6', 'max_cd_prox6', 'min_cd_prox7', 'max_cd_prox7',
       'min_cd_prox8', 'max_cd_prox8', 'min_cd_prox9', 'max_cd_prox9',
       'min_cd_prox10', 'max_cd_prox10'],
      dtype='object')

In [ ]:
print(btc_df.columns.get_loc("stop_loss"))
print(btc_df.columns.get_loc("alvo_gain1"))
print(btc_df.columns.get_loc("alvo_gain2"))
print(btc_df.columns.get_loc("min_cd_prox1"))
print(btc_df.columns.get_loc("max_cd_prox1"))
print(btc_df.columns.get_loc("min_cd_prox10"))
print(btc_df.columns.get_loc("max_cd_prox10"))

14
15
16
17
18
35
36

In [ ]:
btc_df[btc_df.columns[12]]

date
2021-01-01    False
2021-01-02    False
2021-01-03    False
2021-01-04    False
2021-01-05    False
              ...
2021-12-27    False
2021-12-28    False
2021-12-29    False
2021-12-30    False
2021-12-31    False
Name: Compra_ativ_2cd, Length: 365, dtype: bool

Muitas formas potenciais de calcular: pivot table, if, while, rolling (axis =1)...<p>
Vamos usar esse mais simples como feito no anterior

In [ ]:
for i in range(1,11):
  print('btc_df["Loss_',i,'"] = btc_df["min_cd_prox',i,'"] < btc_df["stop_loss"]',sep='')
  print('btc_df["Gain1_',i,'"] = btc_df["max_cd_prox',i,'"] > btc_df["alvo_gain1"]',sep='')
  print('btc_df["Gain2_',i,'"] = btc_df["max_cd_prox',i,'"] > btc_df["alvo_gain2"]',sep='')

btc_df["Loss_1"] = btc_df["min_cd_prox1"] < btc_df["stop_loss"]
btc_df["Gain1_1"] = btc_df["max_cd_prox1"] > btc_df["alvo_gain1"]
btc_df["Gain2_1"] = btc_df["max_cd_prox1"] > btc_df["alvo_gain2"]
btc_df["Loss_2"] = btc_df["min_cd_prox2"] < btc_df["stop_loss"]
btc_df["Gain1_2"] = btc_df["max_cd_prox2"] > btc_df["alvo_gain1"]
btc_df["Gain2_2"] = btc_df["max_cd_prox2"] > btc_df["alvo_gain2"]
btc_df["Loss_3"] = btc_df["min_cd_prox3"] < btc_df["stop_loss"]
btc_df["Gain1_3"] = btc_df["max_cd_prox3"] > btc_df["alvo_gain1"]
btc_df["Gain2_3"] = btc_df["max_cd_prox3"] > btc_df["alvo_gain2"]
btc_df["Loss_4"] = btc_df["min_cd_prox4"] < btc_df["stop_loss"]
btc_df["Gain1_4"] = btc_df["max_cd_prox4"] > btc_df["alvo_gain1"]
btc_df["Gain2_4"] = btc_df["max_cd_prox4"] > btc_df["alvo_gain2"]
btc_df["Loss_5"] = btc_df["min_cd_prox5"] < btc_df["stop_loss"]
btc_df["Gain1_5"] = btc_df["max_cd_prox5"] > btc_df["alvo_gain1"]
btc_df["Gain2_5"] = btc_df["max_cd_prox5"] > btc_df["alvo_gain2"]
btc_df["Loss_6"] = btc_df["min_cd_prox6"] < btc_df["stop_loss"]
btc_df["Gain1_6"] = btc_df["max_cd_prox6"] > btc_df["alvo_gain1"]
btc_df["Gain2_6"] = btc_df["max_cd_prox6"] > btc_df["alvo_gain2"]
btc_df["Loss_7"] = btc_df["min_cd_prox7"] < btc_df["stop_loss"]
btc_df["Gain1_7"] = btc_df["max_cd_prox7"] > btc_df["alvo_gain1"]
btc_df["Gain2_7"] = btc_df["max_cd_prox7"] > btc_df["alvo_gain2"]
btc_df["Loss_8"] = btc_df["min_cd_prox8"] < btc_df["stop_loss"]
btc_df["Gain1_8"] = btc_df["max_cd_prox8"] > btc_df["alvo_gain1"]
btc_df["Gain2_8"] = btc_df["max_cd_prox8"] > btc_df["alvo_gain2"]
btc_df["Loss_9"] = btc_df["min_cd_prox9"] < btc_df["stop_loss"]
btc_df["Gain1_9"] = btc_df["max_cd_prox9"] > btc_df["alvo_gain1"]
btc_df["Gain2_9"] = btc_df["max_cd_prox9"] > btc_df["alvo_gain2"]
btc_df["Loss_10"] = btc_df["min_cd_prox10"] < btc_df["stop_loss"]
btc_df["Gain1_10"] = btc_df["max_cd_prox10"] > btc_df["alvo_gain1"]
btc_df["Gain2_10"] = btc_df["max_cd_prox10"] > btc_df["alvo_gain2"]

In [ ]:
btc_df["Loss_1"] = btc_df["min_cd_prox1"] < btc_df["stop_loss"]
btc_df["Gain1_1"] = btc_df["max_cd_prox1"] > btc_df["alvo_gain1"]
btc_df["Gain2_1"] = btc_df["max_cd_prox1"] > btc_df["alvo_gain2"]
btc_df["Loss_2"] = btc_df["min_cd_prox2"] < btc_df["stop_loss"]
btc_df["Gain1_2"] = btc_df["max_cd_prox2"] > btc_df["alvo_gain1"]
btc_df["Gain2_2"] = btc_df["max_cd_prox2"] > btc_df["alvo_gain2"]
btc_df["Loss_3"] = btc_df["min_cd_prox3"] < btc_df["stop_loss"]
btc_df["Gain1_3"] = btc_df["max_cd_prox3"] > btc_df["alvo_gain1"]
btc_df["Gain2_3"] = btc_df["max_cd_prox3"] > btc_df["alvo_gain2"]
btc_df["Loss_4"] = btc_df["min_cd_prox4"] < btc_df["stop_loss"]
btc_df["Gain1_4"] = btc_df["max_cd_prox4"] > btc_df["alvo_gain1"]
btc_df["Gain2_4"] = btc_df["max_cd_prox4"] > btc_df["alvo_gain2"]
btc_df["Loss_5"] = btc_df["min_cd_prox5"] < btc_df["stop_loss"]
btc_df["Gain1_5"] = btc_df["max_cd_prox5"] > btc_df["alvo_gain1"]
btc_df["Gain2_5"] = btc_df["max_cd_prox5"] > btc_df["alvo_gain2"]
btc_df["Loss_6"] = btc_df["min_cd_prox6"] < btc_df["stop_loss"]
btc_df["Gain1_6"] = btc_df["max_cd_prox6"] > btc_df["alvo_gain1"]
btc_df["Gain2_6"] = btc_df["max_cd_prox6"] > btc_df["alvo_gain2"]
btc_df["Loss_7"] = btc_df["min_cd_prox7"] < btc_df["stop_loss"]
btc_df["Gain1_7"] = btc_df["max_cd_prox7"] > btc_df["alvo_gain1"]
btc_df["Gain2_7"] = btc_df["max_cd_prox7"] > btc_df["alvo_gain2"]
btc_df["Loss_8"] = btc_df["min_cd_prox8"] < btc_df["stop_loss"]
btc_df["Gain1_8"] = btc_df["max_cd_prox8"] > btc_df["alvo_gain1"]
btc_df["Gain2_8"] = btc_df["max_cd_prox8"] > btc_df["alvo_gain2"]
btc_df["Loss_9"] = btc_df["min_cd_prox9"] < btc_df["stop_loss"]
btc_df["Gain1_9"] = btc_df["max_cd_prox9"] > btc_df["alvo_gain1"]
btc_df["Gain2_9"] = btc_df["max_cd_prox9"] > btc_df["alvo_gain2"]
btc_df["Loss_10"] = btc_df["min_cd_prox10"] < btc_df["stop_loss"]
btc_df["Gain1_10"] = btc_df["max_cd_prox10"] > btc_df["alvo_gain1"]
btc_df["Gain2_10"] = btc_df["max_cd_prox10"] > btc_df["alvo_gain2"]

In [ ]:
## Filtrar apenas os com entrada de compra ativada
compras_ativadas_1cd_df = btc_df[btc_df.Compra_ativ_1cd == True]
compras_ativadas_2cd_df = btc_df[btc_df.Compra_ativ_2cd == True]
compras_ativadas_2cd_df

                open      high       low  ...  Loss_10  Gain1_10  Gain2_10
date                                      ...
2021-03-05  277237.0  283451.0  266390.0  ...     True      True     False
2021-03-16  317383.0  322436.0  305262.0  ...     True      True     False
2021-03-23  303155.0  310000.0  296252.0  ...    False      True      True
2021-04-04  332809.0  338597.0  328095.0  ...     True     False     False
2021-05-30  182731.0  192127.0  176727.0  ...     True      True      True
2021-06-22  160890.0  169364.0  145000.0  ...    False      True      True
2021-06-26  158466.0  163250.0  151151.0  ...     True      True      True
2021-07-30  204489.0  220513.0  196501.0  ...     True     False     False
2021-08-04  200087.0  208797.0  196700.0  ...     True     False     False
2021-08-05  207081.0  216025.0  194836.0  ...     True     False     False
2021-08-18  238868.0  246890.0  236712.0  ...     True     False     False
2021-08-25  253287.0  259475.0  250397.0  ...     True      True     False
2021-09-01  245634.0  254560.0  242717.0  ...    False      True     False
2021-09-29  224358.0  231450.0  223094.0  ...     True      True      True
2021-10-23  345006.0  351244.0  340000.0  ...     True      True      True
2021-10-28  329076.0  353296.0  326742.0  ...    False     False     False
2021-11-06  342834.0  346195.0  337858.0  ...     True      True      True
2021-11-17  335435.0  339998.0  327052.0  ...    False      True      True
2021-11-19  321252.0  329492.0  314003.0  ...    False      True      True
2021-11-23  319149.0  328734.0  314000.0  ...    False      True      True
2021-12-11  267706.0  283000.0  265000.0  ...     True      True      True
2021-12-18  262968.0  269499.0  259301.0  ...    False      True      True
2021-12-26  288492.0  292796.0  283013.0  ...     True     False     False

[23 rows x 67 columns]

In [ ]:
compras_ativadas_2cd_df.columns

Index(['open', 'high', 'low', 'close', 'min_2cd_ant', 'Regra1', 'fech_cd_ant',
       'Regra2', 'sinal_compra', 'max_cd_sig_prox', 'max_cd_sig_prox2',
       'Compra_ativ_1cd', 'Compra_ativ_2cd', 'range', 'stop_loss',
       'alvo_gain1', 'alvo_gain2', 'min_cd_prox1', 'max_cd_prox1',
       'min_cd_prox2', 'max_cd_prox2', 'min_cd_prox3', 'max_cd_prox3',
       'min_cd_prox4', 'max_cd_prox4', 'min_cd_prox5', 'max_cd_prox5',
       'min_cd_prox6', 'max_cd_prox6', 'min_cd_prox7', 'max_cd_prox7',
       'min_cd_prox8', 'max_cd_prox8', 'min_cd_prox9', 'max_cd_prox9',
       'min_cd_prox10', 'max_cd_prox10', 'Loss_1', 'Gain1_1', 'Gain2_1',
       'Loss_2', 'Gain1_2', 'Gain2_2', 'Loss_3', 'Gain1_3', 'Gain2_3',
       'Loss_4', 'Gain1_4', 'Gain2_4', 'Loss_5', 'Gain1_5', 'Gain2_5',
       'Loss_6', 'Gain1_6', 'Gain2_6', 'Loss_7', 'Gain1_7', 'Gain2_7',
       'Loss_8', 'Gain1_8', 'Gain2_8', 'Loss_9', 'Gain1_9', 'Gain2_9',
       'Loss_10', 'Gain1_10', 'Gain2_10'],
      dtype='object')

In [ ]:
print(compras_ativadas_2cd_df.columns.get_loc("Loss_1"))
print(compras_ativadas_2cd_df.columns.get_loc("Gain2_10"))

37
66

In [ ]:
## Mt complexo ainda
compras_ativadas_2cd_df[compras_ativadas_2cd_df.columns[37:67]]

            Loss_1  Gain1_1  Gain2_1  ...  Loss_10  Gain1_10  Gain2_10
date                                  ...
2021-03-05   False    False    False  ...     True      True     False
2021-03-16   False     True    False  ...     True      True     False
2021-03-23   False     True    False  ...    False      True      True
2021-04-04   False    False    False  ...     True     False     False
2021-05-30   False    False    False  ...     True      True      True
2021-06-22   False    False    False  ...    False      True      True
2021-06-26   False     True    False  ...     True      True      True
2021-07-30   False    False    False  ...     True     False     False
2021-08-04   False    False    False  ...     True     False     False
2021-08-05   False    False    False  ...     True     False     False
2021-08-18   False    False    False  ...     True     False     False
2021-08-25   False     True    False  ...     True      True     False
2021-09-01   False    False    False  ...    False      True     False
2021-09-29   False    False    False  ...     True      True      True
2021-10-23   False     True    False  ...     True      True      True
2021-10-28   False    False    False  ...    False     False     False
2021-11-06   False    False    False  ...     True      True      True
2021-11-17   False    False    False  ...    False      True      True
2021-11-19   False    False    False  ...    False      True      True
2021-11-23   False    False    False  ...    False      True      True
2021-12-11   False    False    False  ...     True      True      True
2021-12-18   False    False    False  ...    False      True      True
2021-12-26   False    False    False  ...     True     False     False

[23 rows x 30 columns]

In [ ]:
compras_ativadas_2cd_df.head()

                open      high       low  ...  Loss_10  Gain1_10  Gain2_10
date                                      ...
2021-03-05  277237.0  283451.0  266390.0  ...     True      True     False
2021-03-16  317383.0  322436.0  305262.0  ...     True      True     False
2021-03-23  303155.0  310000.0  296252.0  ...    False      True      True
2021-04-04  332809.0  338597.0  328095.0  ...     True     False     False
2021-05-30  182731.0  192127.0  176727.0  ...     True      True      True

[5 rows x 67 columns]

In [ ]:
data_range_btc_df = pd.date_range(start='2021-03-01',end='2021-03-10')
btc_df_index_range = btc_df[btc_df.index.isin(data_range_btc_df)]
btc_df_index_range

fig = make_subplots(rows=1, cols=1)

fig.add_trace(go.Candlestick(name='Bitcoin_BRL', x=btc_df_index_range.index, open=btc_df_index_range['open'], high = btc_df_index_range['high'], low=btc_df_index_range['low'], close=btc_df_index_range['close'],showlegend=True), row=1,col=1)
fig.update_yaxes(title_text="<b> Preço Bitcoin (R$)", row=1, col=1)

fig.add_annotation(x='2021-03-05',y=275000, xref="x",yref="y",text="<b>Candle_Sinalizador",showarrow=True,font=dict(family="Courier New, monospace",size=10,color="black"),align="center",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black")
fig.add_annotation(x='2021-03-05',y=283452, xref="x",yref="y",text="<b>Compra Max + 1",showarrow=True,font=dict(family="Courier New, monospace",size=10,color="black"),align="right",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black")
fig.add_trace(go.Scatter(x=['2021-03-05 00:00','2021-03-07 10:00'],y=[283452,283452,283452], mode="lines+text", name="Preço entrada compra",
                         line = dict(color='purple', width=2, dash='dash')),row=1, col=1)
fig.add_annotation(x='2021-03-07',y=283452, xref="x",yref="y",text="<b>Compra ativada",showarrow=True,font=dict(family="Courier New, monospace",size=10,color="black"),align="left",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)

fig.add_trace(go.Scatter(x=['2021-03-05 00:00','2021-03-07 10:00'],y=[266390,266390,266390], mode="lines+text", name="Stop Loss",
                         line = dict(color='red', width=2, dash='dash')),row=1, col=1)
fig.add_annotation(x='2021-03-05',y=266390, xref="x",yref="y",text="<b>Stop Loss",showarrow=True,font=dict(family="Courier New, monospace",size=10,color="black"),align="left",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)

## Alvos Gain

fig.add_trace(go.Scatter(x=['2021-03-05 00:00','2021-03-10 10:00'],y=[300513,300513,300513], mode="lines+text", name="Alvo Gain (Range)",
                         line = dict(color='green', width=2, dash='dash')),row=1, col=1)
fig.add_annotation(x='2021-03-05',y=300513, xref="x",yref="y",text="<b>Alvo Gain (Range)",showarrow=True,font=dict(family="Courier New, monospace",size=10,color="black"),align="left",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)

fig.add_trace(go.Scatter(x=['2021-03-05 00:00','2021-03-10 10:00'],y=[310920,310920,310920], mode="lines+text", name="Alvo Gain (Fibo)",
                         line = dict(color='green', width=2, dash='dash')),row=1, col=1)
fig.add_annotation(x='2021-03-05',y=310920, xref="x",yref="y",text="<b>Alvo Gain (Fibo)",showarrow=True,font=dict(family="Courier New, monospace",size=10,color="black"),align="left",arrowhead=2,
                   arrowsize=1,arrowwidth=2,arrowcolor="black",row=1, col=1)

fig.update_layout(xaxis_rangeslider_visible=False, title_text='Sinal Compra PFR',width=1000 ,height=700)
fig.show()

In [ ]:
compras_ativadas_2cd_df_long = pd.melt(compras_ativadas_2cd_df,ignore_index=False)
compras_ativadas_2cd_df_long

            variable     value
date
2021-03-05      open  277237.0
2021-03-16      open  317383.0
2021-03-23      open  303155.0
2021-04-04      open  332809.0
2021-05-30      open  182731.0
...              ...       ...
2021-11-19  Gain2_10      True
2021-11-23  Gain2_10      True
2021-12-11  Gain2_10      True
2021-12-18  Gain2_10      True
2021-12-26  Gain2_10     False

[1541 rows x 2 columns]

In [ ]:
Loss01 = compras_ativadas_2cd_df_long[(compras_ativadas_2cd_df_long.variable == 'Loss_1') & (compras_ativadas_2cd_df_long.value == True)]
Loss01

Empty DataFrame
Columns: [variable, value]
Index: []

In [ ]:
Gain1_1 = compras_ativadas_2cd_df_long[(compras_ativadas_2cd_df_long.variable == 'Gain1_1') & (compras_ativadas_2cd_df_long.value == True)]
Gain1_1

           variable value
date
2021-03-16  Gain1_1  True
2021-03-23  Gain1_1  True
2021-06-26  Gain1_1  True
2021-08-25  Gain1_1  True
2021-10-23  Gain1_1  True

In [ ]:
Gain2_1 = compras_ativadas_2cd_df_long[(compras_ativadas_2cd_df_long.variable == 'Gain2_1') & (compras_ativadas_2cd_df_long.value == True)]
Gain2_1

Empty DataFrame
Columns: [variable, value]
Index: []

In [ ]:
 = compras_ativadas_2cd_df_long[(compras_ativadas_2cd_df_long.value == True] & compras_ativadas_2cd_df.columns.get_loc()
print(compras_ativadas_2cd_df.columns.get_loc("Loss_1"))

           variable value
date
2021-03-05  Loss_10  True
2021-03-16  Loss_10  True
2021-04-04  Loss_10  True
2021-05-30  Loss_10  True
2021-06-26  Loss_10  True
2021-07-30  Loss_10  True
2021-08-04  Loss_10  True
2021-08-05  Loss_10  True
2021-08-18  Loss_10  True
2021-08-25  Loss_10  True
2021-09-29  Loss_10  True
2021-10-23  Loss_10  True
2021-11-06  Loss_10  True
2021-12-11  Loss_10  True
2021-12-26  Loss_10  True

In [ ]:
compras_ativadas_2cd_df['Detector'] = (1==1)
compras_ativadas_2cd_df['Detector']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

date
2021-03-05    True
2021-03-16    True
2021-03-23    True
2021-04-04    True
2021-05-30    True
2021-06-22    True
2021-06-26    True
2021-07-30    True
2021-08-04    True
2021-08-05    True
2021-08-18    True
2021-08-25    True
2021-09-01    True
2021-09-29    True
2021-10-23    True
2021-10-28    True
2021-11-06    True
2021-11-17    True
2021-11-19    True
2021-11-23    True
2021-12-11    True
2021-12-18    True
2021-12-26    True
Name: Detector, dtype: bool

In [ ]:
lista_resultados = []

preco_atingiu = 'nada'

for i in range(37,len(compras_ativadas_2cd_df.columns)):
  if compras_ativadas_2cd_df[compras_ativadas_2cd_df.columns[i]] == compras_ativadas_2cd_df[compras_ativadas_2cd_df.columns['Detector']]:
    preco_atingiu = compras_ativadas_2cd_df.columns[i]
    lista_resultados.append()
  else:
    pass

IndexError: ignored

In [ ]:
compras_ativadas_2cd_df.columns[37]

'Loss_1'

In [ ]:
compras_ativadas_2cd_df[compras_ativadas_2cd_df.columns[37]]

date
2021-03-05    False
2021-03-16    False
2021-03-23    False
2021-04-04    False
2021-05-30    False
2021-06-22    False
2021-06-26    False
2021-07-30    False
2021-08-04    False
2021-08-05    False
2021-08-18    False
2021-08-25    False
2021-09-01    False
2021-09-29    False
2021-10-23    False
2021-10-28    False
2021-11-06    False
2021-11-17    False
2021-11-19    False
2021-11-23    False
2021-12-11    False
2021-12-18    False
2021-12-26    False
Name: Loss_1, dtype: bool